import React from "react";
import {
  IoAccessibility,
  IoAirplane,
  IoAlarm,
  IoAlbums,
  IoAlertCircle,
  IoAmericanFootball,
  IoArchive,
  IoArrowRedoCircleSharp,
  IoBalloon,
  IoBan,
  IoBarChart,
  IoBarbell,
  IoBasketball,
  IoBeaker,
  IoBed,
  IoBicycle,
  IoBoat,
  IoBody,
  IoBonfire,
  IoBook,
  IoBowlingBall,
  IoBookmark,
  IoBrush,
  IoBug,
  IoBuild,
  IoBulb,
  IoBus,
  IoCafe,
  IoBusiness,
  IoCalculator,
  IoCalendar,
  IoCar,
  IoCamera,
  IoCash,
  IoChatbox,
  IoCheckbox,
  IoClipboard,
  IoCloud,
  IoColorFill,
  IoColorPalette,
  IoColorWand,
  IoConstruct,
  IoCreate,
  IoDice,
  IoDocument,
  IoEar,
  IoEarth,
  IoEasel,
  IoExtensionPuzzle,
  IoEye,
  IoFastFood,
  IoFileTray,
  IoFileTrayStacked,
  IoFilm,
  IoFish,
  IoFlag,
  IoFitness,
  IoFlame,
  IoFlash,
  IoFlashlight,
  IoFlower,
  IoFolder,
  IoFootball,
  IoFootsteps,
  IoGameController,
  IoGift,
  IoGolf,
  IoGlobe,
  IoHammer,
  IoHappy,
  IoHardwareChip,
  IoHeart,
  IoHelpBuoy,
  IoHourglass,
  IoImage,
  IoJournal,
  IoKey,
  IoLanguage,
  IoLaptop,
  IoLeaf,
  IoLibrary,
  IoLockClosed,
  IoLockOpen,
  IoList,
  IoMagnet,
  IoMailOpen,
  IoMail,
  IoMap,
  IoMedal,
  IoMegaphone,
  IoMic,
  IoMoon,
  IoMusicalNotes,
  IoNavigate,
  IoNotifications,
  IoNutrition,
  IoPaperPlane,
  IoPartlySunny,
  IoPaw,
  IoPencil,
  IoPeople,
  IoPerson,
  IoPieChart,
  IoPin,
  IoPodium,
  IoPrint,
  IoPrism,
  IoReceipt,
  IoRestaurant,
  IoRibbon,
  IoRocket,
  IoRose,
  IoSchool,
  IoServer,
  IoShield,
  IoSparkles,
  IoStatsChart,
  IoStar,
  IoStorefront,
  IoSunny,
  IoTelescope,
  IoTennisball,
  IoTerminal,
  IoText,
  IoTicket,
  IoTime,
  IoTrain,
  IoTrophy,
  IoWine,
  IoWater,
  IoWarning
} from "react-icons/io5";

interface IconMap {
  [key: string]: React.ReactNode;
}

export const StringToIcon = (icon: string): React.ReactNode => {
  const iconMap: { [key: string]: React.ReactNode } = {
    Barrierefreiheit: <IoAccessibility />,
    Flugzeug: <IoAirplane />,
    Alarm: <IoAlarm />,
    Alben: <IoAlbums />,
    Warnungskreis: <IoAlertCircle />,
    AmericanFootball: <IoAmericanFootball />,
    Archiv: <IoArchive />,
    Pfeilnachrechts: <IoArrowRedoCircleSharp />,
    Luftballon: <IoBalloon />,
    Verbot: <IoBan />,
    Balkendiagramm: <IoBarChart />,
    Hantel: <IoBarbell />,
    Basketball: <IoBasketball />,
    Becherglas: <IoBeaker />,
    Bett: <IoBed />,
    Fahrrad: <IoBicycle />,
    Boot: <IoBoat />,
    MenschlicherKörper: <IoBody />,
    Lagerfeuer: <IoBonfire />,
    Buch: <IoBook />,
    Bowlingkugel: <IoBowlingBall />,
    Lesezeichen: <IoBookmark />,
    Pinsel: <IoBrush />,
    Käfer: <IoBug />,
    Bau: <IoBuild />,
    Glühbirne: <IoBulb />,
    Bus: <IoBus />,
    Café: <IoCafe />,
    Geschäft: <IoBusiness />,
    Taschenrechner: <IoCalculator />,
    Kalender: <IoCalendar />,
    Auto: <IoCar />,
    Kamera: <IoCamera />,
    Bargeld: <IoCash />,
    Chatbox: <IoChatbox />,
    Checkbox: <IoCheckbox />,
    Zwischenablage: <IoClipboard />,
    Wolke: <IoCloud />,
    Farbfüllung: <IoColorFill />,
    Farbpalette: <IoColorPalette />,
    Farbzauberstab: <IoColorWand />,
    Konstrukt: <IoConstruct />,
    Erstellen: <IoCreate />,
    Würfel: <IoDice />,
    Dokument: <IoDocument />,
    Ohr: <IoEar />,
    Erde: <IoEarth />,
    Staffelei: <IoEasel />,
    Erweiterungspuzzle: <IoExtensionPuzzle />,
    Auge: <IoEye />,
    FastFood: <IoFastFood />,
    Dateiablage: <IoFileTray />,
    GestapelteDateiablage: <IoFileTrayStacked />,
    Film: <IoFilm />,
    Fisch: <IoFish />,
    Flagge: <IoFlag />,
    Fitness: <IoFitness />,
    Flamme: <IoFlame />,
    Blitz: <IoFlash />,
    Taschenlampe: <IoFlashlight />,
    Blume: <IoFlower />,
    Ordner: <IoFolder />,
    Fußball: <IoFootball />,
    Fußspuren: <IoFootsteps />,
    Spielcontroller: <IoGameController />,
    Geschenk: <IoGift />,
    Golf: <IoGolf />,
    Globus: <IoGlobe />,
    Hammer: <IoHammer />,
    Glücklich: <IoHappy />,
    Hardwarechip: <IoHardwareChip />,
    Herz: <IoHeart />,
    Hilfsboje: <IoHelpBuoy />,
    Sanduhr: <IoHourglass />,
    Bild: <IoImage />,
    Journal: <IoJournal />,
    Schlüssel: <IoKey />,
    Sprache: <IoLanguage />,
    Laptop: <IoLaptop />,
    Blatt: <IoLeaf />,
    Bibliothek: <IoLibrary />,
    GeschlossenesSchloss: <IoLockClosed />,
    OffenesSchloss: <IoLockOpen />,
    Liste: <IoList />,
    Magnet: <IoMagnet />,
    OffenerBriefumschlag: <IoMailOpen />,
    Brief: <IoMail />,
    Karte: <IoMap />,
    Medaille: <IoMedal />,
    Megafon: <IoMegaphone />,
    Mikrofon: <IoMic />,
    Mond: <IoMoon />,
    Musiknoten: <IoMusicalNotes />,
    Navigieren: <IoNavigate />,
    Benachrichtigungen: <IoNotifications />,
    Ernährung: <IoNutrition />,
    Papierflugzeug: <IoPaperPlane />,
    TeilweiseSonnig: <IoPartlySunny />,
    Pfote: <IoPaw />,
    Bleistift: <IoPencil />,
    Menschen: <IoPeople />,
    Person: <IoPerson />,
    Kreisdiagramm: <IoPieChart />,
    Stecknadel: <IoPin />,
    Podium: <IoPodium />,
    Drucken: <IoPrint />,
    Prisma: <IoPrism />,
    Beleg: <IoReceipt />,
    Restaurant: <IoRestaurant />,
    Schleife: <IoRibbon />,
    Rakete: <IoRocket />,
    Rose: <IoRose />,
    Schule: <IoSchool />,
    Server: <IoServer />,
    Schild: <IoShield />,
    Funken: <IoSparkles />,
    Statistikdiagramm: <IoStatsChart />,
    Stern: <IoStar />,
    Ladenfront: <IoStorefront />,
    Sonnig: <IoSunny />,
    Teleskop: <IoTelescope />,
    Tennisball: <IoTennisball />,
    Terminal: <IoTerminal />,
    Text: <IoText />,
    Ticket: <IoTicket />,
    Uhr: <IoTime />,
    Zug: <IoTrain />,
    Pokal: <IoTrophy />,
    Wein: <IoWine />,
    Wasser: <IoWater />,
    Warnung: <IoWarning />,
  };

  return iconMap[icon] || null;
};

export const Icons: string[] = [
  "Barrierefreiheit",
  "Flugzeug",
  "Alarm",
  "Alben",
  "Warnungskreis",
  "AmericanFootball",
  "Archiv",
  "Pfeilnachrechts",
  "Luftballon",
  "Verbot",
  "Balkendiagramm",
  "Hantel",
  "Basketball",
  "Becherglas",
  "Bett",
  "Fahrrad",
  "Boot",
  "MenschlicherKörper",
  "Lagerfeuer",
  "Buch",
  "Bowlingkugel",
  "Lesezeichen",
  "Pinsel",
  "Käfer",
  "Bau",
  "Glühbirne",
  "Bus",
  "Café",
  "Geschäft",
  "Taschenrechner",
  "Kalender",
  "Auto",
  "Kamera",
  "Bargeld",
  "Chatbox",
  "Checkbox",
  "Zwischenablage",
  "Wolke",
  "Farbfüllung",
  "Farbpalette",
  "Farbzauberstab",
  "Konstrukt",
  "Erstellen",
  "Würfel",
  "Dokument",
  "Ohr",
  "Erde",
  "Staffelei",
  "Erweiterungspuzzle",
  "Auge",
  "FastFood",
  "Dateiablage",
  "GestapelteDateiablage",
  "Film",
  "Fisch",
  "Flagge",
  "Fitness",
  "Flamme",
  "Blitz",
  "Taschenlampe",
  "Blume",
  "Ordner",
  "Fußball",
  "Fußspuren",
  "Spielcontroller",
  "Geschenk",
  "Golf",
  "Globus",
  "Hammer",
  "Glücklich",
  "Hardwarechip",
  "Herz",
  "Hilfsboje",
  "Sanduhr",
  "Bild",
  "Journal",
  "Schlüssel",
  "Sprache",
  "Laptop",
  "Blatt",
  "Bibliothek",
  "GeschlossenesSchloss",
  "OffenesSchloss",
  "Liste",
  "Magnet",
  "OffenerBriefumschlag",
  "Brief",
  "Karte",
  "Medaille",
  "Megafon",
  "Mikrofon",
  "Mond",
  "Musiknoten",
  "Navigieren",
  "Benachrichtigungen",
  "Ernährung",
  "Papierflugzeug",
  "TeilweiseSonnig",
  "Pfote",
  "Bleistift",
  "Menschen",
  "Person",
  "Kreisdiagramm",
  "Stecknadel",
  "Podium",
  "Drucken",
  "Prisma",
  "Beleg",
  "Restaurant",
  "Schleife",
  "Rakete",
  "Rose",
  "Schule",
  "Server",
  "Schild",
  "Funken",
  "Statistikdiagramm",
  "Stern",
  "Ladenfront",
  "Sonnig",
  "Teleskop",
  "Tennisball",
  "Terminal",
  "Text",
  "Ticket",
  "Uhr",
  "Zug",
  "Pokal",
  "Wein",
  "Wasser",
  "Warnung"
];
